---
title: "JOUR 301 Schedule Fall 2022"
description: ""
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Slides                                                                                                                                   | Assignments                                                                                                                                                                   |
+==========================================================================================================================================+===============================================================================================================================================================================+
| Week 1: [Introduction to course (files, data, and software)](https://mjfrigaard.github.io/FA22-JO%20UR301/slides/intro-to-course.html#1) | Tutorial: [Introduction to the command line](https://mjfriga%20ard.shinyapps.io/command-line/)                                                                                |
|                                                                                                                                          |                                                                                                                                                                               |
| (2022-08-22)                                                                                                                             | Exercises: [Installing R & RStudio](https://mjfri%20gaard.github.io/FA22-JOUR301/ex%20ercises/install-r-rstudio.html)                                                         |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 2: [The RStudio IDE](https://mjfrigaard.github.io/FA22-JO%20UR301/slides/rstudio-ide-intro.html)                                    | Exercises: [The `goodenuffR` package (slides)](https://mjfriga%20ard.github.io/FA22-JOUR301/exer%20cises/intro-to-goodenuffR.html)                                            |
|                                                                                                                                          |                                                                                                                                                                               |
| (2022-08-29)                                                                                                                             | Exercises: [Intro to the goodenuffR package](https:%20//mjfrigaard.github.io/FA22-JOU%20R301/exercises/goodenuffR.html)                                                       |
|                                                                                                                                          |                                                                                                                                                                               |
|                                                                                                                                          | Assignment: [Intro to `goodenuffR`](https://mjfrigaard.git%20hub.io/FA22-JOUR301/assignments%20/wk2-intro-to-goodenuffR.Rmd)                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 3: Labor Day                                                                                                                        |                                                                                                                                                                               |
|                                                                                                                                          |                                                                                                                                                                               |
| (2022-09-05)                                                                                                                             |                                                                                                                                                                               |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 4: [R Markdown](h%20ttps://mjfrigaard.github.io/FA22-JOU%20R301/slides/intro-to-rmarkdown.html)                                     | Exercises: [R Markdown in Practice](https://mjfrigaar%20d.github.io/FA22-JOUR301/exerci%20ses/rmarkdown-in-practice.html)                                                     |
|                                                                                                                                          |                                                                                                                                                                               |
| (2022-09-12)                                                                                                                             | Assignment: [R Markdown in Practice](https://mjfrigaard.git%20hub.io/FA22-JOUR301/assignments%20/wk3-rmarkdown-in-practice.Rmd)                                               |
|                                                                                                                                          |                                                                                                                                                                               |
|                                                                                                                                          | Resources: [R Markdown: The Definitive Guide](https:/%20/bookdown.org/yihui/rmarkdown/)                                                                                       |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 5: *Walk-through week 2 & 3 homeworks*                                                                                              | Tutorial: [Atomic vectors](https://mjfrigaar%20d.shinyapps.io/atomic-vectors/)                                                                                                |
|                                                                                                                                          |                                                                                                                                                                               |
| (2022-09-19)                                                                                                                             | Tutorial: [S3-vectors](https://mjfri%20gaard.shinyapps.io/S3-vectors/)                                                                                                        |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 6: [Introduction to R](https://mjfrigaard.github.io/FA22%20-JOUR301/slides/intro-r-prog.html#1)                                     | Tutorial: [Importing data into RStudio](https://mjfrigaard.github.i%20o/sheetcheatR/tutorials/import.html)                                                                    |
|                                                                                                                                          |                                                                                                                                                                               |
| (2022-09-26)                                                                                                                             |                                                                                                                                                                               |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 7: [Data Visualization with ggplot2 (part 1 )](https://mjfrigaard.github.io/FA22%20-JOUR301/slides/ggp2-part-01.html#1)             | Exercises: [Intro to ggplot2 (part 1)](https://mjfrigaard.github.io/FA22-JOUR301/exercises/intro-to-ggplot2.html)                                                             |
|                                                                                                                                          |                                                                                                                                                                               |
| (2022-10-03)                                                                                                                             | Assignment: [`ggplot2` part 1](https://mjfrigaard.github.io/FA22-JOUR301/assignments/wk5-ggp2-assignment-01.Rmd)                                                              |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 8: [Data manipulation with `dplyr` part 1](https://mjfrigaard.github.io/FA22%20-JOUR301/slides/dplyr-part-01.html#1)                | Reading: [Data Carpentry](https://github.com/mjfrigaard/FA22-JOUR301/raw/main/reading/2015-data-carpentry-david-mimno.pdf)                                                    |
|                                                                                                                                          |                                                                                                                                                                               |
| (2022-10-10)                                                                                                                             | Exercises: [Intro to data manipulation](https://mjfrigaard.github.io/FA22-JOUR301/exercises/intro-to-dplyr.html)                                                              |
|                                                                                                                                          |                                                                                                                                                                               |
|                                                                                                                                          | Assignment: [Intro to `dplyr`](https://mjfrigaard.github.io/FA22-JOUR301/assignments/wk8-intro-to-dplyr.Rmd)                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 9: Data Visualization with `ggplot2` part 2                                                                                         | Tutorial: [Rectangular data in R](https://mjfrigaard.github.io/sheetcheatR/tutorials/rectangles.html)                                                                         |
|                                                                                                                                          |                                                                                                                                                                               |
| (2022-10-17)                                                                                                                             | Tutorial: [Intro to ggplot2 (part 1)](https://mjfrigaard.shinyapps.io/ggp2-01/)                                                                                               |
|                                                                                                                                          |                                                                                                                                                                               |
| -   [Part A](https://mjfrigaard.github.io/FA22-JOUR301/slides/ggp2-part-02a.html#1)                                                      |                                                                                                                                                                               |
|                                                                                                                                          |                                                                                                                                                                               |
| -   [Part B](https://mjfrigaard.github.io/FA22-JOUR301/slides/ggp2-part-02b.html#1)                                                      |                                                                                                                                                                               |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 10:                                                                                                                                 | Reading: [Data's Role in the Disinformation War](https://datajournalism.com/read/longreads/data-role-in-the-disinformation-war)                                               |
|                                                                                                                                          |                                                                                                                                                                               |
| *Walk-through week 8 (`dplyr`) homework*                                                                                                 | Exercises:                                                                                                                                                                    |
|                                                                                                                                          |                                                                                                                                                                               |
| -   [Introduction to the `tidyverse`](https://mjfrigaard.github.io/FA22-JOUR301/slides/intro-to-tidyverse.html#1)                        | -   [Reshaping data in R](https://mjfrigaard.github.io/FA22-JOUR301/exercises/data-reshape.html)                                                                              |
|                                                                                                                                          |                                                                                                                                                                               |
| -   [Data reshaping with `tidyr`](https://mjfrigaard.github.io/FA22-JOUR301/slides/data-reshape.html#1)                                  | -   [Fixing bad graphs](https://mjfrigaard.github.io/FA22-JOUR301/exercises/fixing-bad-graphs-econ.html) (not graded)                                                         |
|                                                                                                                                          |                                                                                                                                                                               |
| (2022-10-24)                                                                                                                             | Assignment: [Reshaping data in R](https://mjfrigaard.github.io/FA22-JOUR301/assignments/wk10-data-reshaping.Rmd)                                                              |
|                                                                                                                                          |                                                                                                                                                                               |
|                                                                                                                                          | Tutorial: [Data Transformation with `dplyr`](https://mjfrigaard.github.io/sheetcheatR/tutorials/dplyr-p1.html)                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 11:                                                                                                                                 | Exercises:                                                                                                                                                                    |
|                                                                                                                                          |                                                                                                                                                                               |
| -   [Data joins with `dplyr`](https://mjfrigaard.github.io/FA22-JOUR301/slides/data-joins.html#1)                                        | -   [Joining Data in R](https://mjfrigaard.github.io/FA22-JOUR301/assignments/wk11-table-joins.html)                                                                          |
| -   [Data Visualization with `ggplot2` part 3](https://mjfrigaard.github.io/FA22-JOUR301/slides/ggp2-part-03.html#1)                     |                                                                                                                                                                               |
|                                                                                                                                          | Reading: [A job interview presentation inspired by the R community](https://www.pipinghotdata.com/posts/2020-08-30-a-job-interview-presentation-inspired-by-the-r-community/) |
| (2022-10-31)                                                                                                                             |                                                                                                                                                                               |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 12:                                                                                                                                 | Assignment:                                                                                                                                                                   |
|                                                                                                                                          |                                                                                                                                                                               |
| -   [Storyboards](https://mjfrigaard.github.io/FA22-JOUR301/slides/storyboards.html#1)                                                   | -   [Storyboard layouts](https://mjfrigaard.github.io/FA22-JOUR301/assignments/wk12-storyboard.Rmd)                                                                           |
|                                                                                                                                          |     -   See the [Storyboards slide deck](https://mjfrigaard.github.io/FA22-JOUR301/slides/storyboards.html#1) for instructions                                                |
| -   Case study: Image files & iteration                                                                                                  |                                                                                                                                                                               |
|                                                                                                                                          | Reading:                                                                                                                                                                      |
| (2022-11-07)                                                                                                                             |                                                                                                                                                                               |
|                                                                                                                                          | -   [The Rise of Investigative Data Journalism](https://github.com/mjfrigaard/FA22-JOUR301/raw/main/reading/2018-the-rise-of-investigative-data-journalism.pdf)               |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 13:                                                                                                                                 | Reading:                                                                                                                                                                      |
|                                                                                                                                          |                                                                                                                                                                               |
| -   [Describing Data](https://mjfrigaard.github.io/FA22-JOUR301/slides/describe-data.html)                                               | -   [What makes writing more readable?](https://pudding.cool/2022/02/plain/)                                                                                                  |
|                                                                                                                                          |                                                                                                                                                                               |
| (2022-11-14)                                                                                                                             | Assignment:                                                                                                                                                                   |
|                                                                                                                                          |                                                                                                                                                                               |
|                                                                                                                                          | -   [dplyr part 2 - table joins](https://mjfrigaard.github.io/FA22-JOUR301/assignments/wk11-table-joins.html)                                                                 |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 14:                                                                                                                                 | Exercises:                                                                                                                                                                    |
|                                                                                                                                          |                                                                                                                                                                               |
| -   Collaborating with Git & GitHub (*under construction*)                                                                               | -   #TidyTuesday data assignment                                                                                                                                              |
|                                                                                                                                          |                                                                                                                                                                               |
| (2022-11-21)                                                                                                                             |                                                                                                                                                                               |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 15:                                                                                                                                 | Exercises: TBD                                                                                                                                                                |
|                                                                                                                                          |                                                                                                                                                                               |
| -   Building websites with R Markdown (*under construction)*                                                                             |                                                                                                                                                                               |
| -   Data Journalism with the `tidyverse`                                                                                                 |                                                                                                                                                                               |
|                                                                                                                                          |                                                                                                                                                                               |
| (2022-11-28)                                                                                                                             |                                                                                                                                                                               |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 16:                                                                                                                                 | Exercises: TBD                                                                                                                                                                |
|                                                                                                                                          |                                                                                                                                                                               |
| (2022-12-05)                                                                                                                             |                                                                                                                                                                               |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Finals                                                                                                                                   |                                                                                                                                                                               |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Extra Credit:                                                                                                                            |                                                                                                                                                                               |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Schedule
